# Configurações do modelo
model:
  name: "gpt-3.5-turbo"
  temperature: 0.7

# Configurações do banco de dados
database:
  default_session: "default"
  default_agent: "OpenAI"
  default_output_format: "json"
  item_type: "item"  # Tipo padrão para itens
  guardrail_type: "output"  # Tipo padrão para guardrails
  metadata_id_field: "id"  # Campo de ID nos metadados

# Configurações de logging
logging:
  truncate_length: 100  # Comprimento máximo para truncar logs

# Configurações de exemplo para testes
example:
  prompt: "Preciso de um sistema de login com autenticação de dois fatores"

# Configurações de resultado
result:
  default_items: []  # Lista vazia padrão para itens
  default_guardrails: []  # Lista vazia padrão para guardrails 