# Configurações do MCP (Model Context Protocol)

# Configurações de logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    stdout: true
    file:
      enabled: true
      path: "logs/mcp_server.log"

# Configurações do LLM
llm:
  default_model: "gpt-3.5-turbo"
  default_temperature: 0.7
  default_format: "json"
  markdown_prompt_prefix: |
    Por favor, formate sua resposta em Markdown com:
    - Títulos e subtítulos
    - Listas
    - Destaques
    - Tabelas quando relevante

    Prompt:

# Configurações do MCP Handler
handler:
  hook: "/prompt-tdd"
  metadata:
    status:
      success: "success"
      error: "error"
    format:
      json: "json"
      markdown: "markdown" 